title: Learning and Loving Guitar Over the Years
theme: minima
author: Dorny100
email: peter.dornan@ntlworld.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to play and love guitar over the years, developing new styles and buying new guitars.

# social links
twitter_username: PeterDornan4 # DO NOT include the @ character, or else the build will fail!
github_username:  Dorny100 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
